### ISSUE TITLE
app will crash when I quit activity

### ISSUE THREAD

**Issue by xuanxuandaoren** [SceneView/sceneview-android#176]
11-01 17:18:20.613  1335 28986 I Camera2ClientBase: Closed Camera 0. Client was: io.github.sceneview.sample.armodelviewer (PID 12868, UID 10289)
11-01 17:18:20.614 12868 12868 I Choreographer: Skipped 38 frames!  The application may be doing too much work on its main thread.
11-01 17:18:20.615 12868 12868 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=19573743 latency=635ms procState=2 historyMsgCount=3 (msgIndex=3 wall=609ms seq=239 running=5ms runnable=1ms binder=47ms late=33ms h=android.app.ActivityThread$H w=159)
11-01 17:18:21.165 12868 12868 I native  : I0000 00:00:1667294301.165340   12868 session_lite_c_api.cc:37] Deleting ArSession...
11-01 17:18:21.181 12868 12868 I native  : I0000 00:00:1667294301.181094   12868 android_camera.cc:762] [Camera=1; State=CLOSED] Reset cleanly got to CLOSED state.
11-01 17:18:21.181 12868 12868 I native  : I0000 00:00:1667294301.181312   12868 android_camera.cc:762] [Camera=0; State=CLOSED] Reset cleanly got to CLOSED state.
11-01 17:18:21.181 12868 12868 I native  : I0000 00:00:1667294301.181779   12868 session_lite_c_api.cc:39] Deleted ArSession.
11-01 17:18:21.183 12868 12868 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x6d0 in tid 12868 (e.armodelviewer), pid 12868 (e.armodelviewer)
11-01 17:18:21.236   778   778 I tombstoned: received crash request for pid 12868
11-01 17:18:21.237 13097 13097 I crash_dump64: performing dump of process 12868 (target tid = 12868)
11-01 17:18:21.243 13097 13097 F DEBUG   : pid: 12868, tid: 12868, name: e.armodelviewer  >>> io.github.sceneview.sample.armodelviewer <<<
11-01 17:18:21.641  1754  3956 I ActivityManager: Process io.github.sceneview.sample.armodelviewer (pid 12868) has died: fg  TOP 
11-01 17:18:21.641  1754  1807 I Process : PerfMonitor : current process killing process group. PID: 12868
11-01 17:18:21.643   788   788 I Zygote  : Process 12868 exited due to signal 11 (Segmentation fault)
11-01 17:18:21.647  1754  1807 I libprocessgroup: Successfully killed process cgroup uid 10289 pid 12868 in 5ms

**Comment by vigit3** [comment]
Your app is running too much in man thread , try using background thread 
Use coroutines scope for handling your app

**Comment by xuanxuandaoren** [comment]
> Your app is running too much in man thread , try using background thread Use coroutines scope for handling your app

I only new a activity and start MainActivity  in samples  ar-model-viewer。it will crash in MainActivity when BackPressed.

```java

class TestActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_test)
        findViewById<Button>(R.id.btn_go_ar).setOnClickListener {
            startActivity(Intent(this,MainActivity::class.java))
        }
    }
}

```

**Comment by vigit3** [comment]
can you upload your codes for better understanding

**Comment by xuanxuandaoren** [comment]
> can you upload your codes for better understanding

`TestActivity.java`

```java
package io.github.sceneview.sample.armodelviewer

import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.Button

class TestActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_test)
        findViewById<Button>(R.id.btn_go_ar).setOnClickListener {
            startActivity(Intent(this,MainActivity::class.java))
        }
    }
}
```
`MainActivity.java`

```java
package io.github.sceneview.sample.armodelviewer

import android.os.Bundle
import android.util.Log
import android.view.Menu
import android.view.MenuItem
import android.view.View
import android.view.ViewGroup
import androidx.appcompat.app.AppCompatActivity
import androidx.appcompat.widget.Toolbar
import androidx.core.view.isGone
import androidx.core.view.isVisible
import com.google.android.material.floatingactionbutton.ExtendedFloatingActionButton
import io.github.sceneview.ar.ArSceneView
import io.github.sceneview.ar.arcore.LightEstimationMode
import io.github.sceneview.ar.arcore.LightEstimator
import io.github.sceneview.ar.node.ArModelNode
import io.github.sceneview.ar.node.PlacementMode
import io.github.sceneview.light.Light
import io.github.sceneview.light.LightInstance
import io.github.sceneview.math.Position
import io.github.sceneview.utils.doOnApplyWindowInsets
import io.github.sceneview.utils.setFullScreen

class MainActivity : AppCompatActivity(R.layout.activity_main) {

    lateinit var sceneView: ArSceneView
    lateinit var loadingView: View
    lateinit var placeModelButton: ExtendedFloatingActionButton
    lateinit var newModelButton: ExtendedFloatingActionButton

    private val TAG = "MainActivity"


    data class Model(
        val fileLocation: String,
        val scaleUnits: Float? = null,
        val placementMode: PlacementMode = PlacementMode.BEST_AVAILABLE,
        val applyPoseRotation: Boolean = true
    )

    val models = listOf(
        Model("models/spiderbot.glb"),
        Model(
            fileLocation = "models/zoe.glb",
            // Display the Tiger with a size of 3 m long
            scaleUnits = 0.5f,
            placementMode = PlacementMode.PLANE_HORIZONTAL,
            applyPoseRotation = false
        ),
        Model(
            fileLocation = "https://sceneview.github.io/assets/models/DamagedHelmet.glb",
            placementMode = PlacementMode.INSTANT,
            scaleUnits = 0.5f
        ),
        Model(
            fileLocation = "https://storage.googleapis.com/ar-answers-in-search-models/static/GiantPanda/model.glb",
            placementMode = PlacementMode.PLANE_HORIZONTAL,
            // Display the Tiger with a size of 1.5 m height
            scaleUnits = 1.5f
        ),
        Model(
            fileLocation = "https://sceneview.github.io/assets/models/Spoons.glb",
            placementMode = PlacementMode.PLANE_HORIZONTAL_AND_VERTICAL,
            // Keep original model size
            scaleUnits = null
        ),
        Model(
            fileLocation = "https://sceneview.github.io/assets/models/Halloween.glb",
            placementMode = PlacementMode.PLANE_HORIZONTAL,
            scaleUnits = 2.5f
        ),
    )
    var modelIndex = 0
    var modelNode: ArModelNode? = null

    var isLoading = false
        set(value) {
            field = value
            loadingView.isGone = !value
        }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        setFullScreen(
            findViewById(R.id.rootView),
            fullScreen = true,
            hideSystemBars = false,
            fitsSystemWindows = false
        )

        setSupportActionBar(findViewById<Toolbar>(R.id.toolbar)?.apply {
            doOnApplyWindowInsets { systemBarsInsets ->
                (layoutParams as ViewGroup.MarginLayoutParams).topMargin = systemBarsInsets.top
            }
            title = ""
        })
        sceneView = findViewById(R.id.sceneView)



        sceneView.lightEstimationMode = LightEstimationMode.DISABLED
        loadingView = findViewById(R.id.loadingView)
        newModelButton = findViewById<ExtendedFloatingActionButton>(R.id.newModelButton).apply {
            // Add system bar margins
            val bottomMargin = (layoutParams as ViewGroup.MarginLayoutParams).bottomMargin
            doOnApplyWindowInsets { systemBarsInsets ->
                (layoutParams as ViewGroup.MarginLayoutParams).bottomMargin =
                    systemBarsInsets.bottom + bottomMargin
            }
            setOnClickListener { newModelNode() }
        }
        placeModelButton = findViewById<ExtendedFloatingActionButton>(R.id.placeModelButton).apply {
            setOnClickListener { placeModelNode() }
        }

        newModelNode()
    }

    override fun onCreateOptionsMenu(menu: Menu?): Boolean {
        menuInflater.inflate(R.menu.activity_main, menu)
        return super.onCreateOptionsMenu(menu)
    }

    override fun onOptionsItemSelected(item: MenuItem): Boolean {
        item.isChecked = !item.isChecked
        modelNode?.detachAnchor()
        modelNode?.placementMode = when (item.itemId) {
            R.id.menuPlanePlacement -> PlacementMode.PLANE_HORIZONTAL_AND_VERTICAL
            R.id.menuInstantPlacement -> PlacementMode.INSTANT
            R.id.menuDepthPlacement -> PlacementMode.DEPTH
            R.id.menuBestPlacement -> PlacementMode.BEST_AVAILABLE
            else -> PlacementMode.DISABLED
        }
        return super.onOptionsItemSelected(item)
    }

    fun placeModelNode() {
        modelNode?.anchor()
        placeModelButton.isVisible = false
        sceneView.planeRenderer.isVisible = false
    }

    fun newModelNode() {
        isLoading = true
        modelNode?.takeIf { !it.isAnchored }?.let {
            sceneView.removeChild(it)
            it.destroy()
        }
        val model = models[modelIndex]
        modelIndex = (modelIndex + 1) % models.size
        modelNode = ArModelNode(model.placementMode).apply {
            applyPoseRotation = model.applyPoseRotation
            loadModelAsync(
                context = this@MainActivity,
                lifecycle = lifecycle,
                glbFileLocation = model.fileLocation,
                autoAnimate = true,
                scaleToUnits = model.scaleUnits,
                // Place the model origin at the bottom center
                centerOrigin = Position(y = -1.0f)
            ) {
                sceneView.planeRenderer.isVisible = true
                isLoading = false
            }
            onAnchorChanged = { node, _ ->
                placeModelButton.isGone = node.isAnchored
            }
            onHitResult = { node, _ ->
                placeModelButton.isGone = !node.isTracking
            }
        }
        sceneView.addChild(modelNode!!)
        // Select the model node by default (the model node is also selected on tap)
        sceneView.selectedNode = modelNode
    }
}
```

**Comment by kustraslawomir** [comment]
@ThomasGorisse @xuanxuandaoren @vigit3

**Comment by kustraslawomir** [comment]
2022-11-28 12:01:51.809 13175-13175/io.github.sceneview.sample.armodelviewer E/native: E0000 00:00:1669633311.809612   13175 scheduler.cc:278] INTERNAL: RET_CHECK failure (third_party/mediapipe/framework/scheduler.cc:278) state_ != STATE_NOT_STARTED (0 vs. 0) 
    Stack trace:
2022-11-28 12:01:51.809 13175-13175/io.github.sceneview.sample.armodelviewer E/native: E0000 00:00:1669633311.809660   13175 normal_detector_cpu.cc:231] Error graph_->WaitUntilIdle():INTERNAL: RET_CHECK failure (third_party/mediapipe/framework/scheduler.cc:278) state_ != STATE_NOT_STARTED (0 vs. 0) 
    === Source Location Trace: === 
    third_party/mediapipe/framework/scheduler.cc:278
    third_party/mediapipe/framework/calculator_graph.cc:845
2022-11-28 12:01:51.817 1806-3335/? E/SecHAL: nfc_data_callback: [Cmd]Received a response packet : data_sending_flag = false!!
2022-11-28 12:01:51.817 1690-3304/? E/libnfc_nci: [ERROR:nfc_ncif.cc(1457)] nfc_ncif_proc_deactivate - evt_data.deactivate.reason 0, nfc_cb.deact_reason = 0
2022-11-28 12:01:51.817 1806-1806/? E/SecHAL: nfc_hal_write: [Cmd]Send EVT data_sending_flag = true, return size=18!!
2022-11-28 12:01:51.826 1806-3335/? E/SecHAL: nfc_data_callback: [Cmd]Received a response packet : data_sending_flag = false!!
2022-11-28 12:01:52.060 430-430/? E/vold: getUsedF2fsFileNode -> Cannot Get Used FileNode Number (errno=25 Inappropriate ioctl for device)
2022-11-28 12:01:52.251 13175-13175/io.github.sceneview.sample.armodelviewer A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x6d0 in tid 13175 (e.armodelviewer), pid 13175 (e.armodelviewer)
2022-11-28 12:01:52.591 13391-13391/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

**Comment by jamesC21** [comment]
I'm running into the same issue with SEGV_MAPERR.  I have a simple way to repo though which is simply enabling layout inspector when running samples/model-viewer. Crash every time with 0.9.0.
With the latest, running samples/model-viewer directly in the repo, it also crashes when enabling layout inspector this time with ending with this.
        at io.github.sceneview.nodes.Node.destroy(Node.kt:262)
        at io.github.sceneview.nodes.CameraNode.destroy(CameraNode.kt:53)
        at io.github.sceneview.SceneView.destroy(SceneView.kt:693)
        at io.github.sceneview.SceneView$setLifecycle$3.invoke(SceneView.kt:718)
        at io.github.sceneview.SceneView$setLifecycle$3.invoke(SceneView.kt:718)
E/AndroidRuntime:     at com.gorisse.thomas.lifecycle.LifecycleKt$observe$1.onDestroy(Lifecycle.kt:164)
        at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:51)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
        at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:290)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:308)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:151)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3352)
        at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:781)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:335)
        at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:771)
        at androidx.fragment.app.SpecialEffectsController$Operation.cancel(SpecialEffectsController.java:615)
        at androidx.fragment.app.SpecialEffectsController.forceCompleteAllOperations(SpecialEffectsController.java:350)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2980)
        at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2931)
        at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:346)
        at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:259)
        at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:280)
        at android.app.Activity.performDestroy(Activity.java:8319)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1376)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5413)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5459)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5759)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5675)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:62)
        at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5742)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2262)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

Please help with a fix (even if I can just do it locally that would be much appreciated).  
I adding logging in MainFragment onDestroyView() override and it dies After super.onDestroyView()

**Comment by sameerjj** [comment]
I got some more logs that were a bit more helpful. I was able to reproduce on the sample app `sample-ar-cursor-placement` with an introduced additional dummy launcher activity with a button that launches the provided `Activity`

```
20:06:42.977  E  E0000 00:00:1670893602.977739   28618 scheduler.cc:278] INTERNAL: RET_CHECK failure (third_party/mediapipe/framework/scheduler.cc:278) state_ != STATE_NOT_STARTED (0 vs. 0) 
                 Stack trace:
20:06:42.977  E  E0000 00:00:1670893602.977776   28618 normal_detector_cpu.cc:233] Error graph_->WaitUntilIdle():INTERNAL: RET_CHECK failure (third_party/mediapipe/framework/scheduler.cc:278) state_ != STATE_NOT_STARTED (0 vs. 0) 
                 === Source Location Trace: === 
                 third_party/mediapipe/framework/scheduler.cc:278
                 third_party/mediapipe/framework/calculator_graph.cc:845
20:06:43.556  E  in destroy:959
                 reason: destroying material "base_lit_opaque" but 8 instances still alive
20:06:43.556  E  
20:06:43.669  A  Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 28618 (y.direct_relief), pid 28618 (y.direct_relief)
20:06:44.284  A  Cmdline: com.app.balcony.direct_relief
20:06:44.284  A  pid: 28618, tid: 28618, name: y.direct_relief  >>> com.app.balcony.direct_relief <<<
20:06:44.284  A        #00 pc 00000000000cbca0  /data/app/~~n6dZR_hsLeFIyUwdXVKWTQ==/com.app.balcony.direct_relief-mMLFF8DeW3UYAwuxMHnHQA==/base.apk!libfilament-jni.so (BuildId: 566f8cb854d0326e1c1af97cea1dd2f3831c599b)
```

**Comment by ryust** [comment]
I'm experiencing the same Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR) error when exiting back to a parent activity. The GLB is only 15k in size.

**Comment by sameerjj** [comment]
heads up that very possible this will be fixed by https://github.com/SceneView/sceneview-android/pull/150. Not sure though, just heads up in case anyone is in dire need.

**Comment by UnicornJin** [comment]
Also facing the similar problem. 
I'm using the sceneView in something like bottom navigation Fragment. When I switch the fragment from the one with sceneView to another one. The app will crash and seems there's something wrong with the destroy process.

**Comment by jklitsie** [comment]
We also had this problem on back navigation. We got it working by  replacing the lifecycle = lifecycle with :
```kotlin
 loadModelAsync(
                context = requireContext(),
                lifecycle = lifecycle,
                lifecycle = requireActivity().lifecycle,
                glbFileLocation = "models/spiderbot.glb"
            )
```

But this will only work if you are running a single activity type in your application, I would see this crashing when you would navigate back towards a activity that hasn't been initialized.

**Comment by ryust** [comment]
None of the above has helped with the crashes. Has anyone gotten this to work doing an exit of AppCompatActivity with a SceneView in it?

**Comment by tamashalcyon** [comment]
> #150

This will "mute" your crash because your app will be already in the background when the crash happens, so you won't see it :) It's definitely an issue with the destroy process, I can't imagine any workaround for it.

**Comment by ryust** [comment]
Any more progress on this issue?

**Comment by AdrienBotrel** [comment]
For the moment, the only way I found to don't have this issue is to have only one activity and several fragment and to don't destroy the fragment containing the arSceneView when I want to use an other fragment.
So so fragment with the arSceneview continue to consume some ressources in the background but at least the app doesn't crash

**Comment by ryust** [comment]
I've done something similar by putting the ArSceneView in a dialog that I hide instead of dismiss/cancel, but the camera stays on after returning back to the parent activity. This can look suspicious to the user when the camera indicator shows it's active. How did you handle that?

**Comment by AdrienBotrel** [comment]
I'm using this function when I press the back button:
`private fun backToMainMenu(){
        val fragment : Fragment = MainMenuFragment()

        val manager : FragmentManager = supportFragmentManager

        // Begin the fragment transition using support fragment manager
        val transaction: FragmentTransaction = manager.beginTransaction()

        // Replace the fragment on container
        transaction.replace(R.id.containerFragment, fragment)

        // Finishing the transition
        transaction.commit()
    }`

With this code, the fragment where I have my arSceneView is Stopped but not Destroyed. So the camera is closed (normally) and the app doesn't crash.
But if this parent activity is closed, the fragment is also closed and the app crash. So the issue is not solved but only pushed back

**Comment by ThomasGorisse** [comment]
Fixed in [v0.9.2](https://github.com/SceneView/sceneview-android/releases/tag/v1.0.1-sceneview)

**Comment by m-paunovic-vegait** [comment]
This still seems to be an issue in v0.9.2.

**Comment by ThomasGorisse** [comment]
@m-paunovic-vegait Are you sure it's the same issue? Can you send your logs?

**Comment by ThomasGorisse** [comment]
@m-paunovic-vegait Can you make a test with [v0.9.3](https://github.com/SceneView/sceneview-android/releases/tag/v1.0.2-sceneview)

**Comment by ryust** [comment]
I still get the "Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)" error when exiting a fragment with ArSceneView back to the calling activity. Both 0.9.2 and 0.9.3 fail.

Is there a test case that was used to valid the error as resolved? Maybe looking at the code I could do something similar.

**Comment by ThomasGorisse** [comment]
It's quite hard for me to debug since not all your logs show the same thing.
Since it might depends on your usage (Flutter, multiple activities, self destroy calls), could you please all help debugging the destroy call that is throwing the crash?
- Ctrl+Click on `observe()` here https://github.com/SceneView/sceneview-android/blob/f08c2689d4397c2177958b37d48cf299127ed927/sceneview/src/main/java/io/github/sceneview/model/GLBLoader.kt#L69
- Add a breakpoint on the destroy call
![image](https://user-images.githubusercontent.com/6597529/213400621-922e9c8d-166e-465a-924e-a29cfa955b4a.png)
- Add a breakpoint here: https://github.com/SceneView/sceneview-android/blob/f08c2689d4397c2177958b37d48cf299127ed927/sceneview/src/main/java/io/github/sceneview/SceneView.kt#L658
- Add a breakpoint here: https://github.com/SceneView/sceneview-android/blob/c00654b5348dbe27e03a1304965fa87ab452b1ef/sceneview/src/main/java/io/github/sceneview/Filament.kt#L105

The goal is to F7 on Filament destroys so we find the one that is throwing a runtime exception (Double destroy, Instance not released before class,...)

Thanks

**Comment by ThomasGorisse** [comment]
Please check [v0.9.4](https://github.com/SceneView/sceneview-android/releases/tag/v1.0.3-sceneview)

**Comment by m-paunovic-vegait** [comment]
v0.9.4 no longer crashes for me.

**Comment by ryust** [comment]
0.9.4 also works for me. Thanks for getting this issue resolved!

**Comment by vedprakashwagh** [comment]
@ThomasGorisse The crashes are back in 0.9.5 version whenever I go back. I had to search for this issue in order to find the reason, but reverting back to 0.9.4 fixed it for me.

Here's the error -

`Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x110 in tid 7304 (myappid), pid 7304 (myappid)

pid: 7304, tid: 7304, name: myappid  >>> myappid <<<
2023-02-02 18:47:21.334  7544-7544  DEBUG                   crash_dump64                         A        #00 pc 00000000001ce494  /data/app/~~ndZOfziN33j0aLA9-J7bcw==/myappid-r_D_W4qeV5gz75r50UHj0Q==/base.apk!libgltfio-jni.so (filament::gltfio::FilamentAsset::getAssetInstanceCount() const+0) (BuildId: 1f80989e9281f45e9e1be04a9226cfdef6f2338b)
`

**Comment by ThomasGorisse** [comment]
Sorry about that, 0.9.5 uses the latest Filament version that completely renew the model asset and instances usage.
Could you please fix this destroy issue @vedprakashwagh ?

**Comment by vedprakashwagh** [comment]
@ThomasGorisse I'm sorry but I actually have zero experience about this library or AR in general since I just started exploring this yesterday. I'm afraid I might inadvertently make things worse, haha.

**Comment by sameerjj** [comment]
Hi @ThomasGorisse, I'm quite out of my wheelhouse on this one but trying my best to help fix this issue on 0.9.5.

Essentially, the destroy that crashes the app is the first call to `asset.destroy()`  after `filament.destroy()` has already been called. The `_assetLoader` is set to null, so it is reinstantiated from  the call to `Filament.assetLoader` in `asset.destroy()`, that works fine, but the subsequent call to `AssetLoader.nDestroyAsset(mNativeObject, asset.getNativeObject());` seems to crash the app.

https://github.com/sameerjj/sceneview-android/tree/sameer-debug-destroy-crash

I have a forked branch here that has a MainActivity in `sample/ar-cursor-placement` which allows for easy reproduction of the issue. 

Hoping this provides some help!

**Comment by ThomasGorisse** [comment]
Hi @sameerjj
Nice investigation !!!
Could you make a Pull Request with it?
You should be able to directly create from your fork.
Thanks

**Comment by sameerjj** [comment]
Thanks @ThomasGorisse, done :)

**Comment by james-wemoms** [comment]
Hi everyone !
Is there any news regarding this issue as this crash makes this library unusable for me :(
